services:
  api:
    build:
      context: ..
      dockerfile: ./docker/api/Dockerfile
    ports:
      - "${API_PORT}:8001"
  web:
    build:
      context: ..
      dockerfile: ./docker/web/Dockerfile
    ports:
      - "${WEB_PORT}:6543"
    environment:
      - API_URL=http://api:8001
