"""Added done field

Revision ID: a7bafbf9c51b
Revises: 52e754162fc0
Create Date: 2023-06-05 12:45:25.497776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7bafbf9c51b'
down_revision = '52e754162fc0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('done', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'done')
    # ### end Alembic commands ###
